// 权限枚举
export enum Permission {
  // 用户管理
  USER_MANAGE = 'USER_MANAGE',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_VIEW = 'USER_VIEW',
  USER_EDIT = 'USER_EDIT',

  // 角色管理
  ROLE_MANAGE = 'ROLE_MANAGE',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_EDIT = 'ROLE_EDIT',

  // 课程管理
  COURSE_MANAGE = 'COURSE_MANAGE',
  COURSE_CREATE = 'COURSE_CREATE',
  COURSE_UPDATE = 'COURSE_UPDATE',
  COURSE_DELETE = 'COURSE_DELETE',
  COURSE_VIEW = 'COURSE_VIEW',
  COURSE_EDIT = 'COURSE_EDIT',

  // 开课管理
  COURSE_OFFERING_MANAGE = 'COURSE_OFFERING_MANAGE',
  COURSE_OFFERING_CREATE = 'COURSE_OFFERING_CREATE',
  COURSE_OFFERING_UPDATE = 'COURSE_OFFERING_UPDATE',
  COURSE_OFFERING_DELETE = 'COURSE_OFFERING_DELETE',
  COURSE_OFFERING_VIEW = 'COURSE_OFFERING_VIEW',
  COURSE_OFFERING_EDIT = 'COURSE_OFFERING_EDIT',

  // 选课管理
  ENROLLMENT_MANAGE = 'ENROLLMENT_MANAGE',
  ENROLLMENT_APPROVE = 'ENROLLMENT_APPROVE',
  ENROLLMENT_VIEW = 'ENROLLMENT_VIEW',
  ENROLLMENT_CREATE = 'ENROLLMENT_CREATE',
  ENROLLMENT_EDIT = 'ENROLLMENT_EDIT',
  ENROLLMENT_DELETE = 'ENROLLMENT_DELETE',

  // 成绩管理
  GRADE_MANAGE = 'GRADE_MANAGE',
  GRADE_INPUT = 'GRADE_INPUT',
  GRADE_UPDATE = 'GRADE_UPDATE',
  GRADE_VIEW = 'GRADE_VIEW',
  GRADE_EDIT = 'GRADE_EDIT',

  // 排课管理
  SCHEDULE_MANAGE = 'SCHEDULE_MANAGE',
  SCHEDULE_CREATE = 'SCHEDULE_CREATE',
  SCHEDULE_UPDATE = 'SCHEDULE_UPDATE',
  SCHEDULE_DELETE = 'SCHEDULE_DELETE',
  SCHEDULE_VIEW = 'SCHEDULE_VIEW',
  SCHEDULE_EDIT = 'SCHEDULE_EDIT',

  // 学籍管理
  STUDENT_STATUS_MANAGE = 'STUDENT_STATUS_MANAGE',
  STUDENT_STATUS_UPDATE = 'STUDENT_STATUS_UPDATE',
  STUDENT_STATUS_VIEW = 'STUDENT_STATUS_VIEW',

  // 奖惩管理
  REWARD_PUNISHMENT_MANAGE = 'REWARD_PUNISHMENT_MANAGE',
  REWARD_PUNISHMENT_CREATE = 'REWARD_PUNISHMENT_CREATE',
  REWARD_PUNISHMENT_UPDATE = 'REWARD_PUNISHMENT_UPDATE',
  REWARD_PUNISHMENT_DELETE = 'REWARD_PUNISHMENT_DELETE',
  REWARD_PUNISHMENT_VIEW = 'REWARD_PUNISHMENT_VIEW',

  // 系统管理
  SYSTEM_MANAGE = 'SYSTEM_MANAGE',
  DEPARTMENT_MANAGE = 'DEPARTMENT_MANAGE',
  CLASSROOM_MANAGE = 'CLASSROOM_MANAGE',
  DEPARTMENT_VIEW = 'DEPARTMENT_VIEW',
  DEPARTMENT_CREATE = 'DEPARTMENT_CREATE',
  DEPARTMENT_EDIT = 'DEPARTMENT_EDIT',
  DEPARTMENT_DELETE = 'DEPARTMENT_DELETE',

  // 教师管理
  TEACHER_MANAGE = 'TEACHER_MANAGE',
  TEACHER_VIEW = 'TEACHER_VIEW',
  TEACHER_CREATE = 'TEACHER_CREATE',
  TEACHER_EDIT = 'TEACHER_EDIT',
  TEACHER_DELETE = 'TEACHER_DELETE',

  // 学生管理
  STUDENT_MANAGE = 'STUDENT_MANAGE',
  STUDENT_VIEW = 'STUDENT_VIEW',
  STUDENT_CREATE = 'STUDENT_CREATE',
  STUDENT_EDIT = 'STUDENT_EDIT',
  STUDENT_DELETE = 'STUDENT_DELETE',

  // 教师业务
  MY_COURSES_VIEW = 'MY_COURSES_VIEW',
  STUDENT_LIST_VIEW = 'STUDENT_LIST_VIEW',

  // 学生业务
  MY_ENROLLMENT_VIEW = 'MY_ENROLLMENT_VIEW',
  MY_GRADE_VIEW = 'MY_GRADE_VIEW'
}

// 角色枚举
export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ACADEMIC_ADMIN = 'ACADEMIC_ADMIN',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT'
}

// 权限模块分组
export const PERMISSION_MODULES = {
  USER: '用户管理',
  ROLE: '角色管理',
  COURSE: '课程管理',
  ENROLLMENT: '选课管理',
  GRADE: '成绩管理',
  SCHEDULE: '排课管理',
  STUDENT_STATUS: '学籍管理',
  REWARD_PUNISHMENT: '奖惩管理',
  SYSTEM: '系统管理'
}
